### ISSUE TITLE
Putting in different types of grid squares/blocks

### ISSUE THREAD

**Issue by adamimos** [awjuliani/neuro-nav#26]
I am interested in implementing an environment wherein grid locations can be "colored" ie can act as observable information to the agent, for instance a red square might signal context A, and a blue square might signal context B, where A and B are different reward contingencies. It does not seem currently trivially possible to do this, but I was wondering if it could be done with some work. If so I wouldn't mind taking a crack at doing so, if I could be pointed in the right direction.

Thanks for this awesome library!

**Comment by awjuliani** [comment]
Hi @adamimos, thanks for taking the time to write this issue. 

Currently there are only two types of objects which can inhabit  grid locations: blocks (walls), and rewards. I have been thinking about adding additional types, and it seems like this could be one such possible type. Is the idea that on different trials in the same environment a different reward function would be used, and the color of one of the locations in the environment would also change to reflect this? I suppose we would want users to be able to specify both the color and location arbitrarily? In that case, I could imagine something similar to the reward location dictionary, which uses the structure: {(x, y): reward_value}. This new feature could be something like: {(x, ,y): (R, G, B)}. Is that what you had in mind? If so, I can point you at the right parts of the code to implement such a thing. I'd also be happy to accept a PR for such a feature as well if you end up making progress.

**Comment by adamimos** [comment]
Yes that's exactly the idea. I'm excited to work on this. While I'm relatively confident I can do the coding, I'm a little less confident in my github abilities. My understanding is that I would create a branch and then create a PR within that branch, and that's how I could work on it, is that correct? I don't want to mess up your code by mistake!

As for the actual changes, from what I can tell the main places to change things would be in the GridEnv class, adding in another attribute to hold the dictionary you described (or I suppose one could even combine it into the reward_loc dict? though maybe thats not all that elegant). And also would have to change the parts of the code that generate the observations.

**Comment by awjuliani** [comment]
No worries. What you'll need to do is to create a fork of the repository. From there, you can make changes (either on the main branch, or a new branch you create on your fork). Once you are ready, you can then make a pull request to this repository and I can take a look at it.

As for how best to change things to be future-proof, I think creating a more complex data structure that contains both rewards and other things might be a good idea. Something like:
```
objects = {
    "rewards": {
        (1, 1): 1.0,
        (5, 4): -1.0,
    },
    "markers": {
        (2, 2): (1, 0.5, 0.5),
    },
}
```

**Comment by adamimos** [comment]
great thanks for the help!

**Comment by awjuliani** [comment]
Let me know if you run into any issues or have questions about implementation!

**Comment by adamimos** [comment]
I think I have the basic functionality working for grid_envs but I was wondering what to do with the graphs. Since they don't have markers I suppose it could just be an objects dict with an empty 'markers' key or it could be an objects dict with only a rewards_loc key?

I think this is important, since ultimately it would be good to have e.g. the utils functions work with either grid_envs or graphs. Any thoughts?

**Comment by awjuliani** [comment]
I very much agree that they should use as similar an API as possible. For now I think it makes sense to go for an objects dictionary with just one sub-dict: rewards.

**Comment by awjuliani** [comment]
Thanks again for helping with this. I've now merged the changes, along with the addition of key and door object types into `main`. They are also now part of release 0.11: https://github.com/awjuliani/neuro-nav/releases/tag/v0.11.0
