### ISSUE TITLE
a few questions

### ISSUE THREAD

**Issue by quendera** [awjuliani/neuro-nav#47]
Hi there!

My task is quite peculiar, in it I have a few requirements. I'm almost at where I want but I have a few questions:

- I would like to make rewards be optional to collect and make that an action (in my task there is a separate action to collect rewards) - how would I go about implementing that?

- My task wraps around: meaning, if you travel to the rightmost edge of the maze, you should appear on the leftmost. I was able to solve this using portals, do you see a better way?

- I would like every action to move my agent 1 step north. - any ideas on how to make it so? So far what I came up with was resetting the env with the new position being 1 + current position, but I want it to happen in the same episode.

- I have different types of rewards (differently valued rewards), is this possible?

My task is [hexxed](http://hexxed.io)

Thank you so much for the incredible package.

Best,
q

**Comment by awjuliani** [comment]
Hi @quendera,

> * My task wraps around: meaning, if you travel to the rightmost edge of the maze, you should appear on the leftmost. I was able to solve this using portals, do you see a better way?

I think that this is a pretty reasonable way of doing it, given the current features of the library. Are there issues you are running into when using this approach? 

> * I would like every action to move my agent 1 step north. - any ideas on how to make it so? So far what I came up with was resetting the env with the new position being 1 + current position, but I want it to happen in the same episode.

You can change the agent position manually between every action. You can just set `env.agent_pos` to be one north of the current position.

> * I have different types of rewards (differently valued rewards), is this possible?

This is something the library currently supports. The "Usage Tutorial" cell #14 contains an example of how to do this: https://github.com/awjuliani/neuro-nav/blob/main/notebooks/usage_tutorial.ipynb

> * I would like to make rewards be optional to collect and make that an action (in my task there is a separate action to collect rewards) - how would I go about implementing that?

This is the trickiest to accomplish with the current library. You would have to change the underlying action space in https://github.com/awjuliani/neuro-nav/blob/main/neuronav/envs/grid_env.py to include an additional action that is the "pick-up action." You'd then have to modify the reward logic to not pick up rewards unless that action is taken. This is the specific logic which would need to change for providing the reward: https://github.com/awjuliani/neuro-nav/blob/main/neuronav/envs/grid_env.py#L786. I think this is a feature which might be more generally useful, so if you do get it working and would like to submit a PR, I'd be happy to review it and integrate it into the library.

**Comment by awjuliani** [comment]
Hi @quendera,

With the PR (#49) merged, I am going to close this issue for now. If you have additional questions or want to keep discussing the features you mention here, please feel free to reopen the issue or make a new one. Thanks again for contributing to the library, and I hope you are able to implement your task in `neuro-nav`!
